const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');

const targetMyProjects = `            <div className="space-y-4 max-h-[450px] overflow-y-auto pr-2">
              {offsetProjects.length === 0 ? (
                <p className="text-white/40 text-sm">{t('No offset projects registered.')}</p>
              ) : (
                offsetProjects.map(proj => (
                  <div key={proj.id} className="p-4 bg-black/40 border border-white/5 rounded-xl flex flex-col justify-between gap-4">
                    <div>
                      <div className="flex justify-between items-start mb-1">
                        <span className={\`text-[10px] uppercase tracking-widest font-bold px-2 py-0.5 rounded \${
                          proj.status === 'registered' ? 'bg-emerald-500/20 text-emerald-400' :
                          proj.status === 'validation' ? 'bg-amber-500/20 text-amber-400' : 'bg-white/10 text-white/60'
                        }\`}>
                          {proj.status === 'draft_pdd' ? 'Draft PDD' : proj.status === 'validation' ? 'In Validation' : 'Registered'}
                        </span>
                        <span className="font-mono text-[10px] text-white/30">{proj.id}</span>
                      </div>
                      <h4 className="font-bold text-white text-lg">{proj.title}</h4>
                      <p className="text-xs text-white/50 mt-1">Location: {proj.location || 'India'} | Type: {proj.project_type}</p>
                      <p className="text-sm text-white/70 mt-2">{proj.description}</p>
                    </div>
                    
                    <div className="flex gap-2">
                      {proj.status === 'draft_pdd' && (
                        <button 
                          className="w-full py-2 bg-emerald-500 text-black hover:bg-emerald-400 rounded text-xs font-bold uppercase tracking-widest transition-colors flex items-center justify-center gap-2"
                          onClick={async () => {
                             setLoading(true);
                             const draftRes = await fetch('/api/offset-projects/generate-pdd', {
                               method: 'POST',
                               headers: { 'Content-Type': 'application/json', 'Authorization': \`Bearer \${token}\` },
                               body: JSON.stringify({
                                  title: proj.title,
                                  description: proj.description,
                                  project_type: proj.project_type,
                                  location: proj.location || 'India'
                                })
                             });
                             if (draftRes.ok) {
                               const pdd = await draftRes.json();
                               const subRes = await fetch(\`/api/offset-projects/\${proj.id}/pdd\`, {
                                 method: 'POST',
                                 headers: { 'Content-Type': 'application/json', 'Authorization': \`Bearer \${token}\` },
                                 body: JSON.stringify(pdd)
                               });
                               if (subRes.ok) alert('PDD Successfully Generated by Guardian AI and Submitted for Validation!');
                               
                               const updated = await fetch('/api/offset-projects', { headers: { 'Authorization': \`Bearer \${token}\` } });
                               if (updated.ok) setOffsetProjects(await updated.json());
                             }
                             setLoading(false);
                          }}
                        >
                          <FileText size={14} /> {t('Generate AI PDD & Submit')}
                        </button>
                      )}
                      {(proj.status === 'validation' || proj.status === 'registered') && (
                        <button
                          onClick={() => handleViewPdd(proj.id)}
                          className="w-full py-2 bg-white/10 text-white hover:bg-white/20 border border-white/5 rounded text-xs font-bold uppercase tracking-widest transition-all flex items-center justify-center gap-2"
                        >
                          <FileText size={14} /> {t('View Generated PDD')}
                        </button>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>
          </Card>`;

const replacementMyProjects = `              <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2 custom-scrollbar">
                {offsetProjects.length === 0 ? (
                  <div className="text-center py-12 border border-dashed border-white/10 rounded-xl bg-white/5">
                    <ClipboardList className="mx-auto text-white/20 mb-3" size={32} />
                    <p className="text-white/40 text-sm">{t('No offset projects registered.')}</p>
                    <p className="text-white/30 text-xs mt-1">{t('Start by registering a new circular economy project.')}</p>
                  </div>
                ) : (
                  offsetProjects.map(proj => (
                    <div key={proj.id} className="p-5 bg-[#0f0f0f] border border-white/10 rounded-xl flex flex-col justify-between gap-4 group hover:border-emerald-500/30 transition-all">
                      <div>
                        <div className="flex justify-between items-start mb-3">
                          <span className={\`text-[10px] uppercase tracking-widest font-bold px-2 py-1 rounded border \${
                            proj.status === 'registered' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                            proj.status === 'validation' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' : 'bg-white/5 text-white/60 border-white/10'
                          }\`}>
                            {proj.status === 'draft_pdd' ? 'Draft PDD' : proj.status === 'validation' ? 'In Validation' : 'Registered'}
                          </span>
                          <span className="font-mono text-xs text-white/40 bg-black px-2 py-1 rounded">{proj.id}</span>
                        </div>
                        <h4 className="font-bold text-white text-lg">{proj.title}</h4>
                        <div className="flex items-center gap-2 mt-2">
                          <span className="text-[10px] uppercase tracking-widest bg-emerald-500/10 text-emerald-400 px-2 py-0.5 rounded">{proj.project_type}</span>
                          <span className="text-xs text-white/50">{proj.location || 'India'}</span>
                        </div>
                        <p className="text-sm text-white/60 mt-3 line-clamp-2">{proj.description}</p>
                      </div>
                      
                      <div className="flex gap-3 mt-2 pt-4 border-t border-white/5">
                        {proj.status === 'draft_pdd' && (
                          <button 
                            className="w-full py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-bold uppercase tracking-widest transition-colors flex items-center justify-center gap-2 shadow-lg shadow-emerald-900/20"
                            onClick={async () => {
                               setLoading(true);
                               const draftRes = await fetch('/api/offset-projects/generate-pdd', {
                                 method: 'POST',
                                 headers: { 'Content-Type': 'application/json', 'Authorization': \`Bearer \${token}\` },
                                 body: JSON.stringify({
                                    title: proj.title,
                                    description: proj.description,
                                    project_type: proj.project_type,
                                    location: proj.location || 'India'
                                  })
                               });
                               if (draftRes.ok) {
                                 const pdd = await draftRes.json();
                                 const subRes = await fetch(\`/api/offset-projects/\${proj.id}/pdd\`, {
                                   method: 'POST',
                                   headers: { 'Content-Type': 'application/json', 'Authorization': \`Bearer \${token}\` },
                                   body: JSON.stringify(pdd)
                                 });
                                 if (subRes.ok) alert('PDD Successfully Generated by Guardian AI and Submitted for Validation!');
                                 
                                 const updated = await fetch('/api/offset-projects', { headers: { 'Authorization': \`Bearer \${token}\` } });
                                 if (updated.ok) setOffsetProjects(await updated.json());
                               }
                               setLoading(false);
                            }}
                          >
                            <FileText size={16} /> {t('Generate AI PDD & Submit')}
                          </button>
                        )}
                        {(proj.status === 'validation' || proj.status === 'registered') && (
                          <button
                            onClick={() => handleViewPdd(proj.id)}
                            className="w-full py-2 bg-white/5 text-white hover:bg-white/10 border border-white/10 rounded-lg text-xs font-bold uppercase tracking-widest transition-all flex items-center justify-center gap-2"
                          >
                            <FileText size={16} /> {t('View Generated PDD')}
                          </button>
                        )}
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </Card>`;

if (code.includes(targetMyProjects)) {
  code = code.replace(targetMyProjects, replacementMyProjects);
  console.log('Replaced My Projects');
} else {
  console.log('My Projects target not found');
}

const targetMethodologies = `            <div className="space-y-3 max-h-[450px] overflow-y-auto pr-2">
              {methodologies.length === 0 ? (
                <p className="text-white/40 text-sm">{t('Loading methodologies...')}</p>
              ) : (
                methodologies.map(meth => (
                  <div key={meth.id} className="p-4 bg-black/40 border border-white/5 rounded-xl">
                    <span className="text-[10px] uppercase tracking-widest text-blue-400 font-bold block mb-1">{meth.sector} Sector</span>
                    <h4 className="font-bold text-white text-sm">{meth.name}</h4>
                    <p className="text-xs text-white/60 mt-1">{meth.description}</p>
                    <p className="text-[10px] font-mono text-white/40 mt-2">ID: {meth.id} | Standards: {meth.standards_body} | Version: {meth.version}</p>
                  </div>
                ))
              )}
            </div>
          </Card>`;

const replacementMethodologies = `              <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2 custom-scrollbar">
                {methodologies.length === 0 ? (
                  <p className="text-white/40 text-sm text-center py-8">{t('Loading methodologies...')}</p>
                ) : (
                  methodologies.map(meth => (
                    <div key={meth.id} className="p-5 bg-[#0f0f0f] border border-white/10 rounded-xl hover:border-blue-500/30 transition-all">
                      <div className="flex justify-between items-start mb-2">
                        <span className="text-[10px] uppercase tracking-widest text-blue-400 font-bold px-2 py-1 bg-blue-500/10 rounded border border-blue-500/20">{meth.sector} Sector</span>
                        <span className="text-[10px] font-mono text-white/40 bg-black px-2 py-1 rounded">ID: {meth.id}</span>
                      </div>
                      <h4 className="font-bold text-white text-base mt-2">{meth.name}</h4>
                      <p className="text-sm text-white/60 mt-2">{meth.description}</p>
                      <div className="mt-4 pt-3 border-t border-white/5 flex gap-4">
                        <p className="text-[10px] font-mono text-white/40 uppercase tracking-widest">Std: <span className="text-white/70">{meth.standards_body}</span></p>
                        <p className="text-[10px] font-mono text-white/40 uppercase tracking-widest">Ver: <span className="text-white/70">{meth.version}</span></p>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </Card>`;

if (code.includes(targetMethodologies)) {
  code = code.replace(targetMethodologies, replacementMethodologies);
  console.log('Replaced Methodologies');
} else {
  console.log('Methodologies target not found');
}

fs.writeFileSync('src/App.tsx', code);
