import { createPool } from '../db/index.ts';
import crypto from 'crypto';
export type CreditType='CCC'|'GREEN_CREDIT';
export type Registry='BEE_ICM'|'GCP_ICFRE';
const pool=createPool();
const expectedRegistry:Record<CreditType,Registry>={CCC:'BEE_ICM',GREEN_CREDIT:'GCP_ICFRE'};
function assertPositive(n:number){if(!Number.isFinite(n)||n<=0)throw new Error('Quantity must be a positive finite number');}
function assertIssuerBoundary(t:CreditType,r:Registry){if(expectedRegistry[t]!==r)throw new Error(`Invalid authoritative issuer boundary for ${t}`);}
function assertKey(k:string){if(!k?.trim()||k.length>200)throw new Error('A valid idempotency key is required');}

export async function getCustodyPosition(positionId:string){
 const r=await pool.query('SELECT * FROM environmental_credit_positions WHERE id=$1',[positionId]);
 if(!r.rows[0])throw new Error('Depository position not found');
 return r.rows[0];
}

export async function createCustodyPosition(input:{creditType:CreditType;registry:Registry;registryAccountId:string;authoritativeCreditReference:string;holderEntityId:string;quantity:number;tradabilityStatus:'TRADABLE'|'NON_TRADABLE';authoritativeVerifiedAt:string;actorUid:string;idempotencyKey:string}){
 assertPositive(input.quantity);assertIssuerBoundary(input.creditType,input.registry);assertKey(input.idempotencyKey);
 if(!input.registryAccountId||!input.authoritativeCreditReference||!input.holderEntityId)throw new Error('Authoritative registry account, credit reference and holder are required');
 if(!input.authoritativeVerifiedAt||Number.isNaN(Date.parse(input.authoritativeVerifiedAt)))throw new Error('Authoritative verification timestamp is required');
 const c=await pool.connect();try{await c.query('BEGIN');const e=await c.query('SELECT * FROM environmental_credit_transactions WHERE idempotency_key=$1 FOR SHARE',[input.idempotencyKey]);if(e.rows[0]){await c.query('COMMIT');return e.rows[0];}const id=crypto.randomUUID();await c.query(`INSERT INTO environmental_credit_positions (id,credit_type,authoritative_registry,registry_account_id,authoritative_credit_reference,holder_entity_id,issued_quantity,available_quantity,authoritative_verified_at,tradability_status) VALUES ($1,$2,$3,$4,$5,$6,$7,$7,$8,$9)`,[id,input.creditType,input.registry,input.registryAccountId,input.authoritativeCreditReference,input.holderEntityId,input.quantity,input.authoritativeVerifiedAt,input.tradabilityStatus]);const tx=await c.query(`INSERT INTO environmental_credit_transactions (id,position_id,transaction_type,quantity,authoritative_transaction_reference,idempotency_key,actor_uid) VALUES ($1,$2,'CUSTODY',$3,$4,$5,$6) RETURNING *`,[crypto.randomUUID(),id,input.quantity,input.authoritativeCreditReference,input.idempotencyKey,input.actorUid]);await c.query('COMMIT');return tx.rows[0];}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}

export async function reservePosition(positionId:string,quantity:number,actorUid:string,idempotencyKey:string,principalUid:string,role?:string){assertPositive(quantity);assertKey(idempotencyKey);const c=await pool.connect();try{await c.query('BEGIN');const e=await c.query('SELECT * FROM environmental_credit_transactions WHERE idempotency_key=$1 FOR SHARE',[idempotencyKey]);if(e.rows[0]){await c.query('COMMIT');return e.rows[0];}const p=await c.query('SELECT * FROM environmental_credit_positions WHERE id=$1 FOR UPDATE',[positionId]);if(!p.rows[0])throw new Error('Depository position not found');const r=p.rows[0];if(!principalUid||!role)throw new Error('Authenticated buyer/operator context is required');if(!['HELD','RESERVED'].includes(r.status))throw new Error('Position is not available for sale');if(r.tradability_status!=='TRADABLE')throw new Error('Authoritative tradability is not confirmed');if(quantity>Number(r.available_quantity))throw new Error('Insufficient available depository inventory');await c.query(`UPDATE environmental_credit_positions SET available_quantity=available_quantity-$1,reserved_quantity=reserved_quantity+$1,status='RESERVED',updated_at=now() WHERE id=$2`,[quantity,positionId]);const tx=await c.query(`INSERT INTO environmental_credit_transactions (id,position_id,transaction_type,quantity,idempotency_key,actor_uid,metadata) VALUES ($1,$2,'RESERVE',$3,$4,$5,$6) RETURNING *`,[crypto.randomUUID(),positionId,quantity,idempotencyKey,actorUid,JSON.stringify({reservedBy:principalUid,role})]);await c.query('COMMIT');return tx.rows[0];}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}

export async function releaseReservation(positionId:string,quantity:number,actorUid:string,idempotencyKey:string){assertPositive(quantity);assertKey(idempotencyKey);const c=await pool.connect();try{await c.query('BEGIN');const e=await c.query('SELECT * FROM environmental_credit_transactions WHERE idempotency_key=$1 FOR SHARE',[idempotencyKey]);if(e.rows[0]){await c.query('COMMIT');return e.rows[0];}const p=await c.query('SELECT * FROM environmental_credit_positions WHERE id=$1 FOR UPDATE',[positionId]);if(!p.rows[0])throw new Error('Depository position not found');if(quantity>Number(p.rows[0].reserved_quantity))throw new Error('Release exceeds reserved quantity');await c.query(`UPDATE environmental_credit_positions SET available_quantity=available_quantity+$1,reserved_quantity=reserved_quantity-$1,status=CASE WHEN reserved_quantity-$1=0 THEN 'HELD' ELSE 'RESERVED' END,updated_at=now() WHERE id=$2`,[quantity,positionId]);const tx=await c.query(`INSERT INTO environmental_credit_transactions (id,position_id,transaction_type,quantity,idempotency_key,actor_uid) VALUES ($1,$2,'RELEASE',$3,$4,$5) RETURNING *`,[crypto.randomUUID(),positionId,quantity,idempotencyKey,actorUid]);await c.query('COMMIT');return tx.rows[0];}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}

/** Local retirement is prohibited: the authoritative programme must confirm retirement first. */
export async function retireCredits(positionId:string,quantity:number,actorUid:string,idempotencyKey:string,reason:string,authoritativeRetirementReference:string){assertPositive(quantity);assertKey(idempotencyKey);if(!reason?.trim())throw new Error('Retirement reason is required');if(!authoritativeRetirementReference?.trim())throw new Error('Authoritative retirement reference is required');const c=await pool.connect();try{await c.query('BEGIN');const e=await c.query('SELECT * FROM environmental_credit_transactions WHERE idempotency_key=$1 FOR SHARE',[idempotencyKey]);if(e.rows[0]){await c.query('COMMIT');return e.rows[0];}const p=await c.query('SELECT * FROM environmental_credit_positions WHERE id=$1 FOR UPDATE',[positionId]);if(!p.rows[0])throw new Error('Depository position not found');const r=p.rows[0];if(quantity>Number(r.available_quantity))throw new Error('Retirement exceeds available quantity');await c.query(`UPDATE environmental_credit_positions SET available_quantity=available_quantity-$1,retired_quantity=retired_quantity+$1,status=CASE WHEN available_quantity-$1=0 AND reserved_quantity=0 THEN 'RETIRED' ELSE status END,updated_at=now() WHERE id=$2`,[quantity,positionId]);const tx=await c.query(`INSERT INTO environmental_credit_transactions (id,position_id,transaction_type,quantity,authoritative_transaction_reference,idempotency_key,actor_uid,metadata) VALUES ($1,$2,'RETIRE',$3,$4,$5,$6,$7) RETURNING *`,[crypto.randomUUID(),positionId,quantity,authoritativeRetirementReference,idempotencyKey,actorUid,JSON.stringify({reason,authoritativeRetirementConfirmed:true})]);await c.query('COMMIT');return tx.rows[0];}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}

export async function confirmAuthoritativeTransfer(input:{positionId:string;quantity:number;actorUid:string;idempotencyKey:string;buyerEntityId:string;authoritativeTransactionReference:string;buyerEligibilityVerified:boolean}){assertPositive(input.quantity);assertKey(input.idempotencyKey);if(!input.buyerEntityId||!input.authoritativeTransactionReference)throw new Error('Authoritative buyer and transfer reference are required');if(!input.buyerEligibilityVerified)throw new Error('Buyer eligibility is not authoritatively verified');const c=await pool.connect();try{await c.query('BEGIN');const e=await c.query('SELECT * FROM environmental_credit_transactions WHERE idempotency_key=$1 FOR SHARE',[input.idempotencyKey]);if(e.rows[0]){await c.query('COMMIT');return e.rows[0];}const p=await c.query('SELECT * FROM environmental_credit_positions WHERE id=$1 FOR UPDATE',[input.positionId]);if(!p.rows[0])throw new Error('Depository position not found');const r=p.rows[0];if(input.quantity>Number(r.reserved_quantity))throw new Error('Transfer exceeds reserved quantity');const buyerPositionId=crypto.randomUUID();await c.query(`UPDATE environmental_credit_positions SET reserved_quantity=reserved_quantity-$1,transferred_quantity=transferred_quantity+$1,status=CASE WHEN available_quantity=0 AND reserved_quantity-$1=0 THEN 'TRANSFERRED' ELSE 'HELD' END,updated_at=now() WHERE id=$2`,[input.quantity,input.positionId]);await c.query(`INSERT INTO environmental_credit_positions (id,credit_type,authoritative_registry,registry_account_id,authoritative_credit_reference,holder_entity_id,issued_quantity,available_quantity,authoritative_verified_at,tradability_status,status,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$7,now(),'TRADABLE','HELD',$8)`,[buyerPositionId,r.credit_type,r.authoritative_registry,r.registry_account_id,r.authoritative_credit_reference,input.buyerEntityId,input.quantity,JSON.stringify({sourcePositionId:input.positionId,sourceTransferReference:input.authoritativeTransactionReference,receivedByAuthoritativeTransfer:true})]);const tx=await c.query(`INSERT INTO environmental_credit_transactions (id,position_id,transaction_type,quantity,buyer_entity_id,authoritative_transaction_reference,idempotency_key,actor_uid,metadata) VALUES ($1,$2,'TRANSFER',$3,$4,$5,$6,$7,$8) RETURNING *`,[crypto.randomUUID(),input.positionId,input.quantity,input.buyerEntityId,input.authoritativeTransactionReference,input.idempotencyKey,input.actorUid,JSON.stringify({buyerPositionId})]);await c.query('COMMIT');return {...tx.rows[0],buyerPositionId};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}

export async function listAvailablePositions(creditType?:CreditType){const q=creditType?`SELECT * FROM environmental_credit_positions WHERE credit_type=$1 AND status IN ('HELD','RESERVED') AND tradability_status='TRADABLE' AND available_quantity>0 ORDER BY created_at DESC`:`SELECT * FROM environmental_credit_positions WHERE status IN ('HELD','RESERVED') AND tradability_status='TRADABLE' AND available_quantity>0 ORDER BY created_at DESC`;return(await pool.query(q,creditType?[creditType]:[])).rows;}
