apiVersion: apps/v1
kind: Deployment
metadata:
  name: rupaykg-core
  labels:
    app: rupaykg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rupaykg
  template:
    metadata:
      labels:
        app: rupaykg
    spec:
      containers:
      - name: backend
        image: gcr.io/rupaykg-national/backend:v1
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rupaykg-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rupaykg-core
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
